; tfree1.g
; called when tool 1 is freed
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Sep 11 2020 20:17:50 GMT+0800 (中國標準時間)

G60 S0
G91
G1 Z3 F6000
M83
G1 E-2 F6000
G1 E-6 F3000
G1 H1 U250 F7000
