; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.1.10+4-LPC on Tue Jan 19 2021 17:25:01 GMT+0800 (中国标准时间)
T0 P0
G91               ; relative positioning
G1 H2 Z5 F6000    ; lift Z relative to current position
G30
 
G1 Z5 F100       ; lift Z relative to current position


