; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Sep 11 2020 20:17:50 GMT+0800 (中國標準時間)
; Wait for set temperatures to be reached
M116 P0
M83
G1 E-3
G1 R0 X0 F4000
G1 R0 Z0
G1 E3
